### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [Codexzier/WeatherStation#1]
In the files "Bmp180.ino" and "Htu21.ino" there is waiting after a `Wire.requestFrom()`.
For example: `while(!Wire.available()) {}`
All that waiting can be removed, and the timeout in "Htu21.ino" in the function "GetMeasurement()" can be removed.
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by Codexzier** [comment]
> In the files "Bmp180.ino" and "Htu21.ino" there is waiting after a `Wire.requestFrom()`.
> For example: `while(!Wire.available()) {}`
> All that waiting can be removed, and the timeout in "Htu21.ino" in the function "GetMeasurement()" can be removed.
> Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

Thanks for the comment. But this part can not remove, well it doesn't run safely on Wemos and Arduino.  Environment.

**Comment by Koepel** [comment]
They can be removed. There is no such thing as waiting after a Wire.requestFrom(). Those lines of code are nonsense code. They do not make things better, they make things worse.

The `Wire.requestFrom()` is blocking. When the `Wire.requestFrom()` returns, the I2C bus activity has completely finished and the received bytes are waiting in a buffer in the Wire library. The `Wire.available()` and `Wire.read()` do not deal with the I2C bus, they only operate on that buffer in the Wire library.

**Comment by Codexzier** [comment]
> They can be removed. There is no such thing as waiting after a Wire.requestFrom(). Those lines of code are nonsense code. They do not make things better, they make things worse.
> 
> The `Wire.requestFrom()` is blocking. When the `Wire.requestFrom()` returns, the I2C bus activity has completely finished and the received bytes are waiting in a buffer in the Wire library. The `Wire.available()` and `Wire.read()` do not deal with the I2C bus, they only operate on that buffer in the Wire library.

Ok, thanks. I had to look to my old code, and I don't know really, why I am writing this obsolete code.
